version: '3.4'

services:
  users.api:
    image: bingetracker
    build:
      context: backend/users
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  
  users.db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: user-admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: userdb
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - users.db
    ports:
      - 5050:80
