version: '3.4'

services:
  avmedia.api:
    image: python
    build:
      context: ./backend
      dockerfile: ./av_media/Dockerfile
    depends_on:
      - avmedia.db
    ports:
      - 8001:8001
  
  avmedia.db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BT_av_media
    ports:
      - 5431:5432

  livros.api:
    image: python
    build:
      context: ./backend
      dockerfile: ./livros_module/Dockerfile
    depends_on:
      - livros.db
    ports:
      - 8000:8000
  
  livros.db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BT_livros
    ports:
      - 5433:5432

  users.api:
    image: bingetracker
    build:
      context: backend/users
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - users.db
    ports:
      - 3000:3000
  
  users.db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: userdb
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - users.db
      - avmedia.db
      - livros.db
    ports:
      - 5050:80
