version: '3.4'

services:
  bingetracker:
    image: bingetracker
    build:
      context: backend/users
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./src/app"]
