# Generated by Django 3.2.9 on 2021-11-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='num_paginas',
            field=models.IntegerField(default=1),
        ),
    ]
