# Generated by Django 3.2.9 on 2021-12-05 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0002_livro_num_paginas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='num_paginas',
        ),
        migrations.AddField(
            model_name='livro',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AddField(
            model_name='livro',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
