# Generated by Django 3.2.9 on 2021-11-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='n_episodes',
        ),
        migrations.AddField(
            model_name='series',
            name='streaming_service',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(default=1)),
                ('n_episodes', models.IntegerField(default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
        ),
    ]
